# Generated by Django 3.2.8 on 2022-03-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Docente', models.CharField(max_length=50)),
                ('apellido_Docente', models.CharField(max_length=50)),
                ('telefono_Docente', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=50)),
                ('direccion_Docente', models.CharField(max_length=120)),
            ],
        ),
    ]
