# Generated by Django 3.2.8 on 2022-03-30 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMunayDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_Periodos', models.IntegerField()),
                ('fecha_Reserva', models.TimeField()),
                ('Fecha_Solicitud_Res', models.TimeField()),
                ('motivo', models.CharField(max_length=256)),
                ('cant_Estudiantes', models.IntegerField()),
                ('Cod_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Grupo', models.CharField(max_length=32)),
                ('Cod_Materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Dicta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.docente')),
                ('Cod_Grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.grupo')),
                ('Cod_Materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Estudiante', models.IntegerField()),
                ('Cod_Reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMunayDB.reserva')),
            ],
        ),
    ]
