# Generated by Django 3.2.8 on 2022-04-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cant_Estudiantes',
            new_name='Cant_Est_Sol',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='Cod_Reserva',
        ),
        migrations.AddField(
            model_name='grupo',
            name='Cant_Inscritos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Cod_Aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.aula'),
        ),
    ]
