# Generated by Django 3.2.8 on 2022-03-31 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Estudiante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dicta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Docente', models.CharField(max_length=50)),
                ('apellido_Docente', models.CharField(max_length=50)),
                ('telefono_Docente', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=50)),
                ('direccion_Docente', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Grupo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_Periodos', models.IntegerField()),
                ('fecha_Reserva', models.TimeField()),
                ('Fecha_Solicitud_Res', models.TimeField()),
                ('motivo', models.CharField(max_length=256)),
                ('cant_Estudiantes', models.IntegerField()),
                ('Cod_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.docente')),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='grupo',
            name='Cod_Materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.materia'),
        ),
        migrations.AddField(
            model_name='dicta',
            name='Cod_Docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.docente'),
        ),
        migrations.AddField(
            model_name='dicta',
            name='Cod_Grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.grupo'),
        ),
        migrations.AddField(
            model_name='dicta',
            name='Cod_Materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.materia'),
        ),
        migrations.AddField(
            model_name='aula',
            name='Cod_Reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.reserva'),
        ),
    ]
