# Generated by Django 3.2.8 on 2022-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0002_auto_20220414_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='Cod_Grupo',
            field=models.IntegerField(null=True),
        ),
    ]
