# Generated by Django 3.2.8 on 2022-04-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0002_auto_20220331_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='direccion_Docente',
        ),
    ]
