# Generated by Django 3.2.8 on 2022-04-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0003_remove_docente_direccion_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='telefono_Docente',
        ),
    ]
