# Generated by Django 3.2.8 on 2022-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0003_grupo_cod_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='Cod_Grupo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
