# Generated by Django 3.2.8 on 2022-04-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0004_alter_grupo_cod_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Cod_Aula',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
