# Generated by Django 3.2.8 on 2022-04-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0005_aula_cod_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_Reserva',
            new_name='Hora_Reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='Fecha_Reserva',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Hora_Solicitud_Res',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_Solicitud_Res',
            field=models.DateField(),
        ),
    ]
