# Generated by Django 3.2.8 on 2022-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Docente', models.CharField(max_length=50)),
                ('apellido_Docente', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Carrera', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_Periodos', models.IntegerField()),
                ('fecha_Reserva', models.TimeField()),
                ('Fecha_Solicitud_Res', models.TimeField()),
                ('motivo', models.CharField(max_length=256)),
                ('cant_Estudiantes', models.IntegerField()),
                ('Cod_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.docente')),
                ('Cod_Materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Estudiante', models.IntegerField()),
                ('Cod_Reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionDB.reserva')),
            ],
        ),
    ]
