# Generated by Django 3.2.8 on 2022-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Grupo',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Materia',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
