# Generated by Django 3.2.8 on 2022-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0002_auto_20220515_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Justificacion',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
