# Generated by Django 3.2.8 on 2022-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0002_auto_20220515_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Cod_Ambiente',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
