# Generated by Django 3.2.8 on 2022-05-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0004_parametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='MaximoReservas',
            field=models.IntegerField(null=True),
        ),
    ]
