# Generated by Django 3.2.8 on 2022-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0005_parametro_maximoreservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='FechaModificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='Motivo',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
