# Generated by Django 3.2.8 on 2022-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0006_auto_20220608_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='HoraModificacion',
            field=models.TimeField(null=True),
        ),
    ]
