# Generated by Django 3.2.8 on 2022-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0006_auto_20220426_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Tipo_Aula',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
