# Generated by Django 3.2.8 on 2022-06-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDB', '0007_parametro_horamodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='Dia_Horarios',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
